### ISSUE TITLE
Merge Python 3.11 numba fixes?

### ISSUE THREAD

**Issue by bradriley** [oyvindln/ld-decode#100]
Is it possible to just merge Happycube's June 18 ld-decode fix?

https://github.com/happycube/ld-decode/pull/861/commits/2cdcf59c3fed7b8792aef945a676d8453a681ecf

With Python 3.11 currently, vhs-decode (and this branch's ld-decode, ld-cut...) always return the following:

```
/opt/homebrew/lib/python3.11/site-packages/lddecode/utils.py:826: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @jit(cache=True)
```

(Running MacOS ARM native via Homebrew, if it matters.)

**Comment by oyvindln** [comment]
It seems this was committed before the other big changes so I can probably merge these commits a bit easier before fixing the other stuff.

**Comment by oyvindln** [comment]
I cherry picked and added this commit so let me know if you're still seeing the warning.
It was past some of the threading changes that require more extensive changes but it was simple enough to add on it's own before starting on that.

**Comment by bradriley** [comment]
This is resolved now; thank you!

(Was on vacation at the time you committed the fix.)
