### ISSUE TITLE
Add Max Voltage to Recommended Amplifier Board

### ISSUE THREAD

**Issue by aldude999** [oyvindln/ld-decode#137]
### Bug Description
On the [CX-Cards](https://github.com/oyvindln/vhs-decode/wiki/CX-Cards) wiki page, it mentions that RMS amplifier boards can be powered by 5 or 12 volt rails on the VCR, then in the example product below it, the "With Pot" board only takes 5V max. It should be mentioned that the recommended board does not take more than 5V.

### Additional Information

The amplifier board contains a large amount of magic smoke.

**Comment by harrypm** [comment]
`The amplifier board contains a large amount of magic smoke.` 

Lmao aint that the truth yeah thats a typo idk how that got in there without the context of 3-5v range only on the RMS chips.

The new amplifyers however do use 12-30v range and LDOs.

**Comment by harrypm** [comment]
![image](https://github.com/oyvindln/vhs-decode/assets/56382624/a13e3da0-bc96-4cd4-9443-0ee1a8b4d974)

Okay thats sorted.
