### ISSUE TITLE
hifi-decode 8mm Invalid Decimal Literal

### ISSUE THREAD

**Issue by aldude999** [oyvindln/ld-decode#143]
### Bug Description

As of the latest [hifi change](https://github.com/oyvindln/vhs-decode/commit/8f30d2d3e648a833c139b9baa5239e917e6ca673), hifi-decode will no longer run because args.H8 was changed to args.8mm in main, and identifiers are not allowed to start with a number in Python.

### Steps to Reproduce

run hifi-decode

### Environment

- Decode version: [Commit 8f30d2d and up](https://github.com/oyvindln/vhs-decode/commit/8f30d2d3e648a833c139b9baa5239e917e6ca673)
- Operating System: Ubuntu

### Additional Information

There is also an error on [line 144](https://github.com/oyvindln/vhs-decode/blob/8f30d2d3e648a833c139b9baa5239e917e6ca673/vhsdecode/hifi/main.py#L144) where a comma is missing after "--gui"

**Comment by harrypm** [comment]
This was on the to do list, will be patched in the next update.
