### ISSUE TITLE
CVBS-Decode hangs with this input

### ISSUE THREAD

**Issue by philpem** [oyvindln/ld-decode#167]
### Checklist

- [✅] I have searched the issues page for any duplicate issues open or closed and confirmed that this bug has not been reported before.
- [✅] I have tested the issue with the current build.
- [✅] I have attached log files, uploaded sample data, and commands used so that the issue can be easily reproduced by the developers.

### Bug Description

When processing the attached FLAC file, `cvbs-decode` hangs until stopped with Ctrl-C.

The attached FLAC file is a minimum test case created from a 3-hour recording via `dd if=SkyMovies_1990-10-12.u8 of=bork.u8 bs=572727 skip=6510 count=30`

### Steps to Reproduce

1. Decompress the FLAC file to get unsigned 8-bit raw samples
2. `cvbs-decode --pal -A --cxadc broken_movies_sample.u8 BrokenMovieTest`

### Expected Behaviour

Video processes normally, producing a valid TBC file.

### Actual Behaviour

After approx. 20 frames, `cvbs-decode` hangs.

### Environment

- Decode version: Git rev 1debbc96eb95
- Operating System: Linux Mint 21 "Vanessa"
- Hardware Used: Intel Core-i5-3570K, 8GB RAM, 2TB HDD

### Additional Information

FLAC file:
[broken_sample.zip](https://github.com/user-attachments/files/17441712/broken_sample.zip)

### Is it related to tbc-video-export?

No.

**Comment by oyvindln** [comment]
Fixed in latest commits
