### ISSUE TITLE
More options gen_chroma_vid_xxx scripts 

### ISSUE THREAD

**Issue by oyvindln** [oyvindln/ld-decode#38]
Would be useful to e.g make do decodes in part, change settings for ld-chroma-decoder etc.

**Comment by harrypm** [comment]
The addition of the following output options would allow for better post handling.

--vcodec 

Lossless Compressed Options: 

FFV1 

Uncompressed Options:

V210 (YUV) / R210 (RGB)

Intermediate (Ready to Edit) 

ProRes / DNxHD


--aspect 

standard (4:3)

widescreen (16:9)

center-crop (16:9 Letterbox Content) 


--resolution

4fsc (928x576 PAL / 928x480 NTSC) 

SD (720x576 PAL / 720x480 NTSC)

VBI (720x608 PAL / 720x508 NTSC)

**Comment by lizardgai4** [comment]
Just forked it and modified gen-chroma-vid.sh to support all options ld-chroma-decode supports.  Also made a pull request for that

**Comment by lizardgai4** [comment]
UPDATE: My changes were merged Aug/1/2022, and they included modifications to the help screen in gen_chroma_vid.sh.  Is this issue now fully resolved?

**Comment by oyvindln** [comment]
Yeah, will make separate issues for any other more specific features later if needed.
