### ISSUE TITLE
computeLineLen returns NaN in some cases

### ISSUE THREAD

**Issue by itewreed** [oyvindln/ld-decode#40]
In some cases, especially when decoding captures where there's blank tape after the recording, the function computeLineLen returns NaN. As NaN cannot be converted to int, an exception is thrown. This behavior showed up in November and continues to the latest commits as of December 7th 2021.

The function is used in ./vhsdecode/process.py and ./lddecode/core.py Both are running into this exception.
A quick and dirty fix I did locally was to check the computed value for NaN and set it to a fixed value of 2560 (PAL), if it returns NaN. Then the script works and decodes flawlessly. I think it's not the best solution, so I opened that issue.

An example capture to reproduce this error can be found here named  tape15_05_ps1.flac https://drive.google.com/drive/folders/1OJXtm2IJcVZc3Q7OC146t5ThWyPPJpEL
It's a recording of a PS1 (PAL version) startup, where it also heavily switches between PAL and NTSC in the first two seconds, thus producing an even more edge case. Decode parameters were --pal --threads 4 --cxadc3 -nld --recheck_phase

**Comment by vonj** [comment]
Excellent test case!
