### ISSUE TITLE
Audio & Timecode Alinment For Muxing 

### ISSUE THREAD

**Issue by harrypm** [oyvindln/ld-decode#44]
As noted with a [conversation with NeXT ](https://discord.com/channels/665557267189334046/665834485975351307/937551468163133450) 

We need a timestamps file on TBC generation to fix potential audio sync issues.

**Comment by tvasenin** [comment]
There are few reasons why we need per-field timestamps:

- VCRs generally don't output exactly 50 or 60000/1001 fields per second, meaning A/V will be out of sync. In most cases, we want to adjust audio to match video with constant frame rate (or just encode as VFR) hence we need timestamps for this. And even if VCR's would do perfect FPS, we would still need timestamp of the first field for proper A/V delay :)
- In case of any local continuity issues (tape damage etc.) it's useful to examine the timestamps for local correction.

**Comment by harrypm** [comment]
@tvasenin Since we how have [Auto Audio Align](https://gitlab.com/wolfre/vhs-decode-auto-audio-align) this issue is now more a matter of extra metadata from HiFi-Decode as mentioned in the improvemnet ticket [#77](https://github.com/oyvindln/vhs-decode/issues/77).
