### ISSUE TITLE
python version of gen_chroma_vid.sh

### ISSUE THREAD

**Issue by oyvindln** [oyvindln/ld-decode#56]
It would be nicer if we ported these to python, or at least had a python variant that could be used on windows and elsewhere where bash isn't readily available.

**Comment by harrypm** [comment]
As mentioned before on the discord might be worth adding the ability to export media from ld-analyse as an add-on in terms of stream-lined handling adding visual framing adjustment & chroma decoder settings etc then its automatically scripted for seamless usage.

Also, we should make .bat versions of the scrips for the windows tools builds that way everything can be done in windows

**Comment by harrypm** [comment]
This has now been achieved with [tbc-video-export](https://github.com/JuniorIsAJitterbug/tbc-video-export/releases/tag/v0.0.10) and docs switchover is underway, this has now allowed 100% native windows suite usage for video. (hifi-decode as of present builds)

Tidbit note of [Vrunk11's](https://discord.com/channels/665557267189334046/1076310579817496576/1150890957831688362)  windows bat script [ld-chroma-yc.bat.txt](https://github.com/oyvindln/vhs-decode/files/12906657/ld-chroma-yc.bat.txt).
