### ISSUE TITLE
ld-decode location and how to make .TBC files

### ISSUE THREAD

**Issue by TheGitMpeg** [oyvindln/ld-decode#59]
Hello. I want to decode a video in NTSC, but I want to know where is the ld-decode? How can I make my first .TBC file without the ld-decode.exe executable? Help, please. Thanks.

**Comment by harrypm** [comment]
There is currently no .EXE of the decoders, please go read the readme & wiki pages before creating duplicate issues. 

https://github.com/oyvindln/vhs-decode/wiki
