### ISSUE TITLE
monochrome output in gen_chroma_vid broken

### ISSUE THREAD

**Issue by oyvindln** [oyvindln/ld-decode#64]
Need to conditionally adjust the filter graph when mono option is requested

**Comment by harrypm** [comment]
[tbc-video-export](https://github.com/JuniorIsAJitterbug/tbc-video-export) now has implimented monocrome standard output 4fsc luma monocrome output via FFmpeg, so this is now a non-issue with the current export workflow, so i'll close this for now.
