### ISSUE TITLE
vhs-decode not decoding properly since recent Video 8 change

### ISSUE THREAD

**Issue by davidvankemenade** [oyvindln/ld-decode#87]
After this commit (https://github.com/happycube/ld-decode/commit/0a8eb3449c38abeea2c47adbc984953ebe2547ea) chroma seems to be broken. I previously decoded a Betamax sample which was perfectly fine. Today, I decoded the same capture file and the chroma was off and unstable over time.

Could it be that some NTSC parameters are applied to PAL?

Working well before last commit:
![PromsGood](https://github.com/oyvindln/vhs-decode/assets/133023311/9da0bae6-3d7c-4ddb-8380-08e34f390e12)

Chroma off after last commit:
![PromsBroken](https://github.com/oyvindln/vhs-decode/assets/133023311/a28c4198-159b-4325-85e3-46ce817c3518)

**Comment by oyvindln** [comment]
Yeah I think I might have accidentally skipped the bits that make it not rotation on the chroma signal on PAL betamax (might have also broken u-matic.)

**Comment by oyvindln** [comment]
Should be sorted in 524b30e31d2cb5fd3625c72d8ff916458ef76080. Betamax still needs some work in general to look correct though.

**Comment by davidvankemenade** [comment]
Many thanks for sorting this out so quickly @oyvindln!

From what I've tried so far, Betamax looks pretty good. What still needs to be optimised?

**Comment by oyvindln** [comment]
The deemphasis filter is rather complicated just like for video8, right now the code is just using a simplified filter which doesn't get the balance quite right. One visible effect deemphasis being off is a smearing effect after sharp transitions. For PAL specifically there is also some performance stuff.
